[greenclip]
  enable_image_support = true
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 200
  max_selection_size_bytes = 0
  trim_space_from_selection = true
  use_primary_selection_as_input = false
  history_file = "/tmp/greenclip.history"
  blacklisted_applications = []
  static_history = []
