format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$character"""

add_newline = false

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
symbol = ""
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
