#!/bin/sh
pgrep -x sxhkd || sxhkd &
dunst &
picom &
greenclip daemon &
fcitx &
xwallpaper --stretch ~/.config/bspwm/wall.png
pgrep bspswallow || bspswallow &

bspc monitor -d 1 2 3 4 5

bspc config focus_follows_pointer	true

bspc config border_width	3
bspc config window_gap		0

bspc config borderless_monocle	true
bspc config ignore_ewmh_focus true
bspc config automatic_scheme alternate

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
